"""kanji and prim elems

Revision ID: 06ed299fa417
Revises: 
Create Date: 2022-05-02 11:50:48.396729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ed299fa417'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kanji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.Column('character', sa.String(length=2), nullable=True),
    sa.Column('character_img', sa.String(length=128), nullable=True),
    sa.Column('meaning', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('story', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('primitive_element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meanings', sa.String(length=64), nullable=True),
    sa.Column('kanji_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['kanji_id'], ['kanji.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('primitive_element')
    op.drop_table('kanji')
    # ### end Alembic commands ###
